branches:
  - main
  - name: next
    prerelease: true
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - publishCmd: "./bump.sh ${nextRelease.version} \"${nextRelease.notes}\""
tagFormat: ${version}
preset: angular
