branches:
  - main
  - name: next
    prerelease: true
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - - "@semantic-release/exec"
    - prepareCmd: "./bump.sh ${nextRelease.version} ${nextRelease.notes}"
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
      message: "chore(release): release ${nextRelease.version} [skip ci]"
tagFormat: ${version}
preset: angular
