.TH POMO 1 "June 2025" "Pomo" "User Commands"

.SH NAME
pomo \- A terminal-based Pomodoro timer

.SH SYNOPSIS
.B pomo

.SH DESCRIPTION
.B pomo
is a terminal-based Pomodoro timer that helps you manage your work sessions and breaks using the Pomodoro Technique.

.SH OPTIONS
.TP
.B \-h, \-\-help
Show help message and exit.

.SH KEY BINDINGS
.TP
.B f
Start a focus session
.TP
.B b
Start a break session
.TP
.B e
End the current session
.TP
.B q
Quit Pomo
.TP
.B ?
Toggle help view

.SH CONFIGURATION
Pomo can be configured using either a YAML configuration file or environment variables.

.TP
.I Configuration File
Create a configuration file at \fI~/.pomo/config.yaml\fR with the following format:

.nf
\fBfocus_duration:\fR 25m
\fBbreak_duration:\fR 5m
\fBsound_enabled:\fR true
.fi

.TP
.I Environment Variables

.TP
.B POMO_FOCUS_DURATION
Duration of focus sessions (e.g., "25m")
.TP
.B POMO_BREAK_DURATION
Duration of break sessions (e.g., "5m")
.TP
.B POMO_SOUND_ENABLED
Enable/disable terminal bell sound (true/false)

.SH SEE ALSO
.BR pomo(7)

.SH AUTHOR
Written by Max Plumley.
