name: Release

on:
  push:
    branches:
      - main
      - next

jobs:
  release:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    environment:
      name: release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install -g semantic-release @semantic-release/exec @semantic-release/changelog @semantic-release/git

      - name: Run semantic-release
        id: semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
      
      - name: Checkout versioned
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.semantic-release.outputs.new_version }}
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: true
      
      - name: Package
        if: steps.semantic-release.outputs.should_release == 'true' 
        uses: goreleaser/goreleaser-action@v4
        with:
          args: build --clean
      
      - name: Release
        if: |
          steps.semantic-release.outputs.should_release == 'true' &&
          github.ref == 'refs/heads/main'
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release --clean --release-notes /tmp/release_notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ steps.semantic-release.outputs.new_version }}
